title: Booklet
description: A starter template for a Jeykll site using the Just the Docs theme!
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs


just_the_docs:
  navigation_depth: 7
  search_enabled: true
  search_indexing: true

callouts:
  note:
    title: Note
    color: purple

mermaid:
  version : "9.1.3"

# Plugins
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby


callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: purple
  important:
    title: Important
    color: green
  note:
    title: Note
    color: grey-dk
  def:
    title: Définition
    color: green