title: Booklet
description: A starter template for a Jeykll site using the Just the Docs theme!
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: thatonedragon.github.io/Booklet

just_the_docs:
  navigation_depth: 8
  search_enabled: true
  search_indexing: true

callouts:
  note:
    title: Note
    color: purple

mermaid:
  version : "9.1.3"

# Plugins
plugins:
 - jekyll-default-layout

callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: purple
  important:
    title: Important
    color: green
  note:
    title: Note
    color: grey-dk
  def:
    title: Définition
    color: green