title: Booklet
description: A starter template for a Jeykll site using the Just the Docs theme!
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://just-the-docs.github.io


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: purple
  important:
    title: Important
    color: green
  note:
    title: Note
    color: grey-dk
  def:
    title: Définition
    color: green